# Generated by Django 6.0.6 on 2026-06-06 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='/profile-Guest.png', null=True, upload_to='profiles/'),
        ),
    ]
