# Generated by Django 5.1.1 on 2026-06-02 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_is_edited'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
    ]
