# Generated by Django 6.0.6 on 2026-06-06 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_remove_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='/ghost.png', null=True, upload_to='posts/'),
        ),
    ]
